"""SQLAlchemy ORM models.

Layout:
  - `auth`     : User, AuditLog
  - `students` : Student, Class, Chapter, StudentProgress
  - `assignments`: Assignment, QuestionSet, Question, Submission, SubmissionImage, Grading
  - `learning` : KnowledgePoint, StudentKnowledgeState(+History), LearningObjective,
                 LearningEvidence, ParentFeedback, LearningPlan(+Item)
  - `materials`: Material, MaterialCandidate
  - `exams`    : Exam, ExamAttempt
  - `historical`: HistoricalAssessment, HistoricalQuestion
  - `question_bank`: QuestionBankItem, QuestionVersion, BankUpdateCandidate
  - `extended` : Textbook/Version/Section, MaterialVersion/Page/Chunk,
                 KnowledgePointVersion, LearningSession, LearningIntervention,
                 StudentAnswer, AnswerVersion, ExamVersion, ExamQuestion,
                 AssignmentVersion, ParentAnnotation, ParentScore,
                 StudentProgressHistory, QuestionEmbedding, QuestionSignature,
                 ErrorPattern, StudentErrorEvidence, MaterialAgentRun,
                 KnowledgeUpdateRun, QuestionBankUpdateRun, ImportReview,
                 ImportReviewItem, Export
  - `system`   : LLMRun, Job, Setting
"""

from app.models.auth import AuditLog, User
from app.models.assignments import (
    Assignment,
    GradeVersion,
    Grading,
    Question,
    QuestionSet,
    Submission,
    SubmissionImage,
)
from app.models.learning import (
    InterventionOutcome,
    KnowledgePoint,
    KnowledgeUpdateCandidate,
    LearningEvidence,
    LearningObjective,
    LearningPlan,
    LearningPlanItem,
    ParentFeedback,
    StudentKnowledgeState,
    StudentKnowledgeStateHistory,
)
from app.models.materials import Material, MaterialCandidate
from app.models.historical import HistoricalAssessment, HistoricalQuestion
from app.models.exams import Exam, ExamAttempt
from app.models.question_bank import BankUpdateCandidate, QuestionBankItem, QuestionVersion
from app.models.students import Chapter, Class, Student, StudentProgress
from app.models.system import Job, LLMRun, Setting
from app.models.extended import (
    AnswerVersion,
    AssignmentVersion,
    ErrorPattern,
    ExamQuestion,
    ExamVersion,
    Export,
    ImportReview,
    ImportReviewItem,
    KnowledgePointVersion,
    KnowledgeUpdateRun,
    LearningIntervention,
    LearningSession,
    MaterialAgentRun,
    MaterialChunk,
    MaterialPage,
    MaterialVersion,
    ParentAnnotation,
    ParentScore,
    QuestionBankUpdateRun,
    QuestionEmbedding,
    QuestionSignature,
    Section,
    StudentAnswer,
    StudentErrorEvidence,
    StudentProgressHistory,
    Textbook,
    TextbookVersion,
)

ALL_MODELS = [
    User,
    Student,
    Class,
    Chapter,
    StudentProgress,
    StudentProgressHistory,
    Assignment,
    AssignmentVersion,
    QuestionSet,
    Question,
    Submission,
    SubmissionImage,
    Grading,
    GradeVersion,
    KnowledgePoint,
    KnowledgePointVersion,
    StudentKnowledgeState,
    StudentKnowledgeStateHistory,
    LearningObjective,
    LearningEvidence,
    ParentFeedback,
    LearningPlan,
    LearningPlanItem,
    LearningIntervention,
    InterventionOutcome,
    Material,
    MaterialVersion,
    MaterialPage,
    MaterialChunk,
    LLMRun,
    AuditLog,
    Setting,
    Job,
    Textbook,
    TextbookVersion,
    Section,
    LearningSession,
    StudentAnswer,
    AnswerVersion,
    ExamVersion,
    ExamQuestion,
    ParentAnnotation,
    ParentScore,
    ErrorPattern,
    StudentErrorEvidence,
    QuestionEmbedding,
    QuestionSignature,
    MaterialAgentRun,
    KnowledgeUpdateRun,
    QuestionBankUpdateRun,
    ImportReview,
    ImportReviewItem,
    Export,
]


def register_all() -> None:
    """Import all model modules so their tables register with the metadata."""
    from app.models import (  # noqa: F401
        assignments,
        auth,
        exams,
        extended,
        historical,
        learning,
        materials,
        question_bank,
        students,
        system,
    )


__all__ = [
    "ALL_MODELS",
    "register_all",
    "User",
    "AuditLog",
    "Student",
    "Class",
    "Chapter",
    "StudentProgress",
    "StudentProgressHistory",
    "Assignment",
    "AssignmentVersion",
    "QuestionSet",
    "Question",
    "Submission",
    "SubmissionImage",
    "Grading",
    "GradeVersion",
    "KnowledgePoint",
    "KnowledgePointVersion",
    "StudentKnowledgeState",
    "StudentKnowledgeStateHistory",
    "LearningObjective",
    "LearningEvidence",
    "ParentFeedback",
    "LearningPlan",
    "LearningPlanItem",
    "LearningIntervention",
    "InterventionOutcome",
    "KnowledgeUpdateCandidate",
    "Material",
    "MaterialVersion",
    "MaterialPage",
    "MaterialChunk",
    "HistoricalAssessment",
    "HistoricalQuestion",
    "Exam",
    "ExamAttempt",
    "ExamVersion",
    "ExamQuestion",
    "QuestionBankItem",
    "QuestionVersion",
    "BankUpdateCandidate",
    "QuestionEmbedding",
    "QuestionSignature",
    "MaterialAgentRun",
    "KnowledgeUpdateRun",
    "QuestionBankUpdateRun",
    "ImportReview",
    "ImportReviewItem",
    "Export",
    "Textbook",
    "TextbookVersion",
    "Section",
    "LearningSession",
    "StudentAnswer",
    "AnswerVersion",
    "ParentAnnotation",
    "ParentScore",
    "ErrorPattern",
    "StudentErrorEvidence",
    "LLMRun",
    "Job",
    "AuditLog",
    "Setting",
]