"""Learning-loop services.

Implements the PRD core loop (§7, §59, §29, §30):
    Learning Evidence -> Student Knowledge State update -> Diagnosis -> Learning Plan

State update model (PRD §59) — an evidence-weighted exponential moving average:
    new = old + lr * (observation - old)
where the learning rate is modulated by question difficulty, evidence trust
level and error type (careless mistakes move mastery far less than real
misunderstandings).

Diagnosis (PRD §29) is deterministic: low mastery, declining trend and decay
risk are combined into a priority ranking. The learning plan (PRD §30–31) is
generated by the LLM when available with this same heuristic as fallback.
"""

from __future__ import annotations

import logging
import math
from datetime import datetime
from typing import Any, Optional

from sqlalchemy.orm import Session

from app.models.assignments import Assignment, Grading, Question, QuestionSet, Submission
from app.models.learning import (
    ERROR_PATTERNS,
    INTERVENTION_TYPES,
    KnowledgePoint,
    LearningEvidence,
    LearningPlan,
    LearningPlanItem,
    StudentKnowledgeState,
    StudentKnowledgeStateHistory,
)
from app.models.students import Chapter, Student

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Tuning constants (PRD §57, §59, §60, §61)
# ---------------------------------------------------------------------------

BASE_LEARNING_RATE = 0.25  # max share of the gap closed by one evidence
DIFFICULTY_WEIGHT = {"easy": 0.85, "medium": 1.0, "hard": 1.15}
TRUST_WEIGHT = {
    "RAW": 0.5,
    "AI_EXTRACTED": 0.7,
    "VALIDATED": 0.85,
    "PARENT_CONFIRMED": 1.0,  # official evidence boundary (PRD §57)
    "OFFICIAL": 1.0,
}
# Careless mistakes say little about knowledge; concept errors say a lot.
ERROR_WEIGHT = {
    "CARELESS_ERROR": 0.45,
    "READING_ERROR": 0.6,
    "CALCULATION_ERROR": 0.75,
    "SIGN_ERROR": 0.8,
    "DIAGRAM_ERROR": 0.85,
}
PASS_THRESHOLD = 60.0  # per-question score (0–100) counted as "correct"

# Spaced review intervals in days by mastery band (PRD §61).
REVIEW_INTERVALS = ((0.4, 1), (0.6, 3), (0.8, 7), (0.9, 14), (1.01, 30))
DECAY_BANDS = ((7, "LOW"), (30, "MEDIUM"), (90, "HIGH"), (float("inf"), "CRITICAL"))

OPEN_ENDED_QTYPES = {"composition", "reading_comprehension"}  # always parent-reviewed
AUTO_CONFIRM_CONFIDENCE = 0.80  # PRD §47–48: below this → needs parent review


# ---------------------------------------------------------------------------
# Knowledge points
# ---------------------------------------------------------------------------

def sync_knowledge_points(db: Session) -> int:
    """Create KnowledgePoint rows from chapter.knowledge_points JSON lists.

    Idempotent: matches on (name, textbook_version, grade). Returns the
    number of newly created rows.
    """
    created = 0
    chapters = db.query(Chapter).all()
    for ch in chapters:
        for name in ch.knowledge_points or []:
            if not name or not str(name).strip():
                continue
            name = str(name).strip()
            exists = (
                db.query(KnowledgePoint)
                .filter(
                    KnowledgePoint.name == name,
                    KnowledgePoint.textbook_version == ch.textbook_version,
                    KnowledgePoint.grade == ch.grade,
                )
                .first()
            )
            if exists:
                if exists.chapter_id is None:
                    exists.chapter_id = ch.id
                continue
            db.add(
                KnowledgePoint(
                    subject="math",
                    name=name,
                    chapter_id=ch.id,
                    grade=ch.grade,
                    textbook_version=ch.textbook_version,
                )
            )
            created += 1
    db.flush()
    return created


def get_or_create_knowledge_point(
    db: Session,
    name: str,
    *,
    grade: Optional[str] = None,
    textbook_version: Optional[str] = None,
    chapter_id: Optional[int] = None,
) -> KnowledgePoint:
    name = (name or "").strip()
    kp = (
        db.query(KnowledgePoint)
        .filter(KnowledgePoint.name == name)
        .order_by(KnowledgePoint.id.asc())
        .first()
    )
    if kp:
        return kp
    kp = KnowledgePoint(
        name=name, grade=grade, textbook_version=textbook_version, chapter_id=chapter_id
    )
    db.add(kp)
    db.flush()
    return kp


# ---------------------------------------------------------------------------
# Evidence recording + state update
# ---------------------------------------------------------------------------

def _observation_score(correct: bool, score: Optional[float]) -> float:
    """Map evidence to an observation in [0, 1]."""
    if score is not None:
        return max(0.0, min(1.0, float(score) / 100.0))
    return 1.0 if correct else 0.0


def compute_decay_risk(last_practiced: Optional[datetime], now: Optional[datetime] = None) -> str:
    if last_practiced is None:
        return "CRITICAL"
    days = ((now or datetime.utcnow()) - last_practiced).days
    for bound, label in DECAY_BANDS:
        if days <= bound:
            return label
    return "CRITICAL"


def review_interval_for(mastery: float) -> int:
    for bound, days in REVIEW_INTERVALS:
        if mastery < bound:
            return days
    return 30


def _apply_evidence(
    db: Session,
    state: StudentKnowledgeState,
    evidence: LearningEvidence,
) -> StudentKnowledgeState:
    """Fold one piece of evidence into the knowledge state (PRD §59)."""
    now = datetime.utcnow()
    obs = _observation_score(evidence.correct, evidence.score)
    diff_w = DIFFICULTY_WEIGHT.get((evidence.difficulty or "medium").lower(), 1.0)
    trust_w = TRUST_WEIGHT.get(evidence.trust_level, 0.6)
    err_w = ERROR_WEIGHT.get(evidence.error_type or "", 1.0)
    lr = max(0.05, min(0.45, BASE_LEARNING_RATE * diff_w * trust_w * err_w))

    old = state.mastery_score
    if state.evidence_count == 0:
        new = round(obs * 0.9, 4)  # conservative first estimate
    else:
        new = round(old + lr * (obs - old), 4)

    state.evidence_count += 1
    state.confidence = round(min(0.97, 1.0 - math.exp(-state.evidence_count / 3.0)), 4)
    delta = new - old
    state.trend = "improving" if delta > 0.02 else "declining" if delta < -0.02 else "stable"
    state.mastery_score = new
    state.last_assessed = now
    state.last_practiced = now
    state.decay_risk = compute_decay_risk(now)
    state.status = "weak" if new < 0.4 else "mastered" if new >= 0.8 else "learning"
    state.review_interval_days = review_interval_for(new)
    state.next_review_at = datetime.fromtimestamp(now.timestamp() + state.review_interval_days * 86400)

    db.add(
        StudentKnowledgeStateHistory(
            student_id=state.student_id,
            knowledge_point_id=state.knowledge_point_id,
            mastery_score=new,
            confidence=state.confidence,
            evidence_id=evidence.id,
            reason=f"{evidence.source_type}/{evidence.trust_level}"
            + (f"/{evidence.error_type}" if evidence.error_type else ""),
            changed_at=now,
        )
    )
    db.flush()
    return state


def get_state(db: Session, student_id: int, knowledge_point_id: int) -> StudentKnowledgeState:
    state = (
        db.query(StudentKnowledgeState)
        .filter(
            StudentKnowledgeState.student_id == student_id,
            StudentKnowledgeState.knowledge_point_id == knowledge_point_id,
        )
        .first()
    )
    if state is None:
        state = StudentKnowledgeState(
            student_id=student_id,
            knowledge_point_id=knowledge_point_id,
            mastery_score=0.0,
            confidence=0.0,
        )
        db.add(state)
        db.flush()
    return state


def record_evidence(
    db: Session,
    *,
    student_id: int,
    knowledge_point_name: Optional[str] = None,
    knowledge_point_id: Optional[int] = None,
    correct: bool,
    score: Optional[float] = None,
    difficulty: Optional[str] = None,
    error_type: Optional[str] = None,
    feedback: Optional[str] = None,
    confidence: Optional[float] = None,
    trust_level: str = "PARENT_CONFIRMED",
    source_type: str = "ASSIGNMENT",
    question_id: Optional[int] = None,
    submission_id: Optional[int] = None,
    observed_by: Optional[int] = None,
    created_at: Optional[datetime] = None,
) -> LearningEvidence:
    """Create a LearningEvidence row and update the knowledge state."""
    if knowledge_point_id is None:
        if not knowledge_point_name:
            raise ValueError("knowledge_point_name or knowledge_point_id is required")
        kp = get_or_create_knowledge_point(db, knowledge_point_name)
        knowledge_point_id = kp.id
    if error_type and error_type not in ERROR_PATTERNS:
        error_type = None  # tolerate unexpected LLM enum values

    evidence = LearningEvidence(
        student_id=student_id,
        question_id=question_id,
        submission_id=submission_id,
        knowledge_point_id=knowledge_point_id,
        knowledge_point_name=knowledge_point_name,
        source_type=source_type,
        correct=correct,
        score=score,
        difficulty=difficulty,
        error_type=error_type,
        feedback=feedback,
        confidence=confidence,
        trust_level=trust_level,
        observed_by=observed_by,
        created_at=created_at or datetime.utcnow(),
    )
    db.add(evidence)
    db.flush()

    state = get_state(db, student_id, knowledge_point_id)
    _apply_evidence(db, state, evidence)

    student = db.get(Student, student_id)
    if student:
        _refresh_weak_points(db, student)
    return evidence


def record_evidence_for_submission(
    db: Session,
    *,
    submission: Submission,
    grading: Grading,
    student: Student,
    observed_by: Optional[int] = None,
) -> int:
    """After parent confirmation, convert the grading into evidence (PRD §49, §56).

    One evidence row per (question, knowledge point). Idempotent: skips if
    evidence for this submission already exists.
    """
    already = (
        db.query(LearningEvidence)
        .filter(LearningEvidence.submission_id == submission.id)
        .first()
    )
    if already:
        return 0

    assignment = db.get(Assignment, submission.assignment_id)
    qs = db.get(QuestionSet, assignment.question_set_id) if assignment else None
    questions: list[Question] = sorted(qs.questions, key=lambda q: q.order) if qs else []

    per_question: list[dict] = []
    raw = grading.per_question_scores
    if isinstance(raw, dict):
        per_question = list(raw.get("per_question") or [])
    elif isinstance(raw, list):
        per_question = list(raw)
    by_order = {entry.get("order"): entry for entry in per_question if isinstance(entry, dict)}

    count = 0
    for q in questions:
        entry = by_order.get(q.order, {})
        score = entry.get("score")
        try:
            score_f = float(score) if score is not None else None
        except (TypeError, ValueError):
            score_f = None
        correct = score_f is not None and score_f >= PASS_THRESHOLD
        error_type = entry.get("error_type") or None
        ai_conf = entry.get("confidence")
        for kp_name in q.knowledge_points or ["未分类"]:
            record_evidence(
                db,
                student_id=student.id,
                knowledge_point_name=str(kp_name),
                correct=correct,
                score=score_f,
                difficulty=q.difficulty,
                error_type=error_type,
                feedback=entry.get("comment"),
                confidence=float(ai_conf) if ai_conf is not None else None,
                trust_level="PARENT_CONFIRMED",
                source_type="ASSIGNMENT",
                question_id=q.id,
                submission_id=submission.id,
                observed_by=observed_by,
                created_at=grading.confirmed_at,
            )
            count += 1

    return count


def _refresh_weak_points(db: Session, student: Student) -> None:
    """Keep students.weak_points in sync with the knowledge states (PRD §26)."""
    rows = (
        db.query(StudentKnowledgeState, KnowledgePoint)
        .join(KnowledgePoint, StudentKnowledgeState.knowledge_point_id == KnowledgePoint.id)
        .filter(StudentKnowledgeState.student_id == student.id)
        .order_by(StudentKnowledgeState.mastery_score.asc())
        .limit(5)
        .all()
    )
    weak = [kp.name for st, kp in rows if st.mastery_score < 0.6]
    if weak:
        student.weak_points = weak


def compute_decay_refresh(db: Session, student_id: Optional[int] = None) -> None:
    """Recompute decay_risk / next_review_at without new evidence (PRD §60)."""
    q = db.query(StudentKnowledgeState)
    if student_id:
        q = q.filter(StudentKnowledgeState.student_id == student_id)
    now = datetime.utcnow()
    for st in q.all():
        st.decay_risk = compute_decay_risk(st.last_practiced, now)
        if st.last_practiced:
            st.next_review_at = datetime.fromtimestamp(
                st.last_practiced.timestamp() + st.review_interval_days * 86400
            )
    db.flush()


# ---------------------------------------------------------------------------
# Diagnosis (PRD §29) — deterministic priority ranking
# ---------------------------------------------------------------------------

def diagnose_student(db: Session, student_id: int) -> dict:
    compute_decay_refresh(db, student_id)
    rows = (
        db.query(StudentKnowledgeState, KnowledgePoint)
        .join(KnowledgePoint, StudentKnowledgeState.knowledge_point_id == KnowledgePoint.id)
        .filter(StudentKnowledgeState.student_id == student_id)
        .all()
    )
    priorities = []
    for st, kp in rows:
        gap = max(0.0, 0.8 - st.mastery_score)  # distance to "mastered"
        score = gap * 10
        if st.trend == "declining":
            score += 2.0
        if st.decay_risk == "HIGH":
            score += 1.5
        elif st.decay_risk == "CRITICAL":
            score += 1.0
        if st.confidence < 0.3 and st.mastery_score < 0.6:
            score += 0.5
        if score <= 0:
            continue
        recent_errors = [
            e.error_type
            for e in db.query(LearningEvidence)
            .filter(
                LearningEvidence.student_id == student_id,
                LearningEvidence.knowledge_point_id == kp.id,
                LearningEvidence.error_type.isnot(None),
            )
            .order_by(LearningEvidence.created_at.desc())
            .limit(5)
            .all()
        ]
        priorities.append(
            {
                "knowledge_point_id": kp.id,
                "knowledge_point": kp.name,
                "mastery": st.mastery_score,
                "confidence": st.confidence,
                "trend": st.trend,
                "decay_risk": st.decay_risk,
                "evidence_count": st.evidence_count,
                "priority_score": round(score, 2),
                "recent_errors": recent_errors[:3],
                "reason": f"掌握度 {int(st.mastery_score * 100)}%，"
                + (
                    f"近 {st.evidence_count} 次练习中常见错误：{', '.join(recent_errors[:2])}；"
                    if recent_errors
                    else ""
                )
                + f"遗忘风险 {st.decay_risk}",
            }
        )
    priorities.sort(key=lambda p: p["priority_score"], reverse=True)
    for i, p in enumerate(priorities, start=1):
        p["rank"] = i
    return {"student_id": student_id, "priorities": priorities[:5]}


# ---------------------------------------------------------------------------
# Learning plan (PRD §30–31) — heuristic builder, LLM optional
# ---------------------------------------------------------------------------

_INTERVENTION_BY_RANK = ["REVIEW", "PRACTICE", "PRACTICE", "PRACTICE", "QUIZ"]
_DIFFICULTY_BY_MASTERY = lambda m: "easy" if m < 0.4 else "medium" if m < 0.7 else "hard"  # noqa: E731


def build_heuristic_plan(db: Session, student: Student, diagnosis: dict,
                         policy: Optional[dict] = None) -> dict:
    """Deterministic 5-day plan from the diagnosis priorities.

    With a learning policy (§94) present, practice days use the intervention
    type that historically moves THIS student's mastery the most.
    """
    practice_type = "PRACTICE"
    if policy:
        from app.services.policy import preferred_practice_type

        practice_type = preferred_practice_type(policy)
    items: list[dict] = []
    priorities = diagnosis.get("priorities", [])[:3]
    if not priorities:
        any_kp = db.query(KnowledgePoint).order_by(KnowledgePoint.id.asc()).first()
        priorities = [
            {
                "knowledge_point_id": any_kp.id if any_kp else None,
                "knowledge_point": any_kp.name if any_kp else "综合练习",
                "mastery": 0.0,
            }
        ]
    for day in range(1, 6):
        if day == 5:
            items.append(
                {
                    "day": 5,
                    "intervention_type": "QUIZ",
                    "knowledge_point_id": priorities[0].get("knowledge_point_id"),
                    "knowledge_point_name": priorities[0].get("knowledge_point"),
                    "description": f"Mini Test：{priorities[0]['knowledge_point']} 综合检测（6 题）",
                    "question_count": 6,
                    "estimated_minutes": 25,
                    "rationale": "检验本周练习效果，形成本轮闭环证据",
                }
            )
            continue
        p = priorities[(day - 1) % len(priorities)]
        kind = _INTERVENTION_BY_RANK[(day - 1) % 4]
        if kind == "PRACTICE" and practice_type != "PRACTICE":
            kind = practice_type  # §94 adaptive sequencing
        mastery = float(p.get("mastery", 0.0))
        if kind == "REVIEW":
            desc = f"复习{p['knowledge_point']}：概念讲解 + 例题 2 道"
            qc, mins = 2, 20
        else:
            desc = f"{p['knowledge_point']} {kind}（{_DIFFICULTY_BY_MASTERY(mastery)} 难度，{6 - day} 道）"
            qc, mins = max(4, 8 - day), 25
        items.append(
            {
                "day": day,
                "intervention_type": kind,
                "knowledge_point_id": p.get("knowledge_point_id"),
                "knowledge_point_name": p.get("knowledge_point"),
                "description": desc,
                "question_count": qc,
                "estimated_minutes": mins,
                "rationale": f"当前掌握度 {int(mastery * 100)}%",
            }
        )
    return {
        "title": f"{student.name} 的 5 天学习计划",
        "summary": "基于知识点掌握度与近期错误的自动规划",
        "items": items,
    }


def generate_plan(db: Session, student: Student, user_id: Optional[int] = None) -> LearningPlan:
    """Generate a DRAFT learning plan: LLM first, heuristic fallback (PRD §30)."""
    diagnosis = diagnose_student(db, student.id)
    policy = None
    try:
        from app.services.policy import learning_policy

        policy = learning_policy(db, student.id)  # §94 adaptive sequencing
    except Exception as exc:  # noqa: BLE001
        logger.warning("policy computation failed: %s", exc)
    plan_data: Optional[dict] = None
    llm_run_id = None
    generated_by = "heuristic"
    try:
        from app.services.llm import stage_learning_plan  # lazy: needs langchain

        states = _states_payload(db, student.id)
        plan_data, run_id = stage_learning_plan(
            db,
            student_payload={
                "name": student.name,
                "grade": student.grade,
                "textbook": student.textbook_version,
                "weak_points": student.weak_points or [],
                "strengths": student.strengths or [],
            },
            diagnosis=diagnosis,
            states=states,
            user_id=user_id,
        )
        llm_run_id = run_id
        generated_by = "ai"
        if not isinstance(plan_data, dict) or not plan_data.get("items"):
            plan_data = None
    except Exception as exc:  # noqa: BLE001
        logger.warning("LLM plan generation failed, falling back to heuristic: %s", exc)

    if plan_data is None:
        plan_data = build_heuristic_plan(db, student, diagnosis, policy=policy)

    plan = LearningPlan(
        student_id=student.id,
        title=str(plan_data.get("title") or f"{student.name} 的学习计划")[:128],
        summary=plan_data.get("summary"),
        diagnosis_json=diagnosis,
        status="draft",
        generated_by=generated_by,
        llm_run_id=llm_run_id,
    )
    db.add(plan)
    db.flush()
    for item in plan_data.get("items", []):
        itype = str(item.get("intervention_type", "PRACTICE")).upper()
        if itype not in INTERVENTION_TYPES:
            itype = "PRACTICE"
        try:
            qc = max(0, min(30, int(item.get("question_count", 0) or 0)))
        except (TypeError, ValueError):
            qc = 0
        db.add(
            LearningPlanItem(
                plan_id=plan.id,
                day=int(item.get("day", len(plan_data["items"]))),
                intervention_type=itype,
                knowledge_point_id=item.get("knowledge_point_id"),
                knowledge_point_name=item.get("knowledge_point_name")
                or item.get("knowledge_point"),
                description=str(item.get("description", "")).strip() or "学习任务",
                question_count=qc,
                estimated_minutes=item.get("estimated_minutes"),
                rationale=item.get("rationale"),
            )
        )
    db.flush()
    return plan


def _states_payload(db: Session, student_id: int) -> list[dict]:
    rows = (
        db.query(StudentKnowledgeState, KnowledgePoint)
        .join(KnowledgePoint, StudentKnowledgeState.knowledge_point_id == KnowledgePoint.id)
        .filter(StudentKnowledgeState.student_id == student_id)
        .all()
    )
    return [
        {
            "knowledge_point": kp.name,
            "mastery": st.mastery_score,
            "confidence": st.confidence,
            "trend": st.trend,
            "decay_risk": st.decay_risk,
            "evidence_count": st.evidence_count,
        }
        for st, kp in rows
    ]


def grading_triage(per_question: list[dict], qtypes: list[str]) -> tuple[Optional[float], bool]:
    """PRD §47–48: compute overall confidence + needs_review flag.

    Returns (overall_confidence | None, needs_review).
    """
    confs = []
    for entry in per_question:
        c = entry.get("confidence") if isinstance(entry, dict) else None
        if c is not None:
            try:
                confs.append(max(0.0, min(1.0, float(c))))
            except (TypeError, ValueError):
                pass
    overall = round(sum(confs) / len(confs), 4) if confs else None
    needs_review = (
        overall is None
        or overall < AUTO_CONFIRM_CONFIDENCE
        or any(qt in OPEN_ENDED_QTYPES for qt in qtypes)
    )
    return overall, needs_review
